# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        doc_config:
            contentsCss: 'css/ckeditor_document.css'
            bodyClass: 'document-editor'
            format_tags: 'p;h1;h2;h3;pre'
            height: 800
            width: 1200
            extraPlugins: 'wordcount,notification'
            toolbar: [ [ 'Print' ], [ 'Undo', 'Redo' ], [ 'Format', 'Font', 'FontSize' ], [ 'Bold', 'Italic', 'Underline', 'Strike', 'RemoveFormat', 'CopyFormatting' ], [ 'TextColor', 'BGColor' ], [ 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' ], [ 'Link', 'Unlink' ], [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote' ], [ 'Image', 'Table' ], [ 'Maximize' ] ]
    plugins:
        wordcount:
            path:     "/bundles/plugins/wordcount/" # with trailing slash
            filename: "plugin.js"
        notification:
            path:     "/bundles/plugins/notification/" # with trailing slash
            filename: "plugin.js"
