# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        doc_config:
            contentsCss: 'css/ckeditor_document.css'
            bodyClass: 'document-editor'
            format_tags: 'p;h1;h2;h3;pre'
            height: '85vh'
            width: '70vw'
            toolbar: [ [ 'Styles' ], [ 'Undo', 'Redo' ], [ 'Font', 'FontSize' ], [ 'Bold', 'Italic', 'Underline', 'Strike', 'RemoveFormat', 'CopyFormatting' ], [ 'TextColor', 'BGColor' ], [ 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' ], [ 'Link', 'Unlink' ], [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote' ], [ 'Image', 'Table' ], [ 'Maximize' ] , [ 'About' ]]
            allowedContent: 'p h2 h3 h4 img{text-align,margin-left}(*); a[!href,target]{*}(*); table th tr td strong s em; ol ul li span(*){font-size,font-family,color,background-color}[data-id]; img[*]{*}; '
            extraPlugins: ['wordcount', 'notification']
            stylesSet: 'elw_styles:/ckeditor_styles.js'
        simple_config:
            toolbar: [ [ 'Undo', 'Redo' ], [ 'Font', 'FontSize' ] [ 'Bold', 'Italic'],  [ 'TextColor', 'BGColor' ], [ 'Link', 'Unlink' ], [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent' ]]
            allowedContent: 'p h2 h3 h4 img{text-align,margin-left}(*); a[!href,target]{*}(*); table th tr td strong s em; ol ul li span(*){font-size,font-family,color,background-color}[data-id]; img[*]{*}; '
            extraPlugins: ['wordcount', 'notification']
    plugins:
        wordcount:
            path:     "/plugins/wordcount/" # with trailing slash
            filename: "plugin.js"
        notification:
            path:     "/plugins/notification/" # with trailing slash
            filename: "plugin.js"
