knp_snappy:
    process_timeout: 120
    pdf:
        enabled:    true
        binary:     '%kernel.project_dir%%env(WKHTMLTOPDF_PATH)%'
        options:    []
    image:
        enabled:    true
        binary:     '%kernel.project_dir%%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
