lti1p3:
    key_chains:
        toolKey:
            key_set_name: "toolSet"
            public_key: "file://%kernel.project_dir%/config/secrets/public.key"
            private_key: "file://%kernel.project_dir%/config/secrets/private.key"
            private_key_passphrase: null
    platforms:
        ugatest2:
            name: "elc"
            audience: "https://ugatest2.view.usg.edu"
            oidc_authentication_url: "https://ugatest2.view.usg.edu/d2l/lti/authenticate"
            oauth2_access_token_url: "https://auth.brightspace.com/core/connect/token"
        elc:
            name: "elc"
            audience: "https://uga.view.usg.edu"
            oidc_authentication_url: "https://uga.view.usg.edu/d2l/lti/authenticate"
            oauth2_access_token_url: "https://auth.brightspace.com/core/connect/token"
    tools:
        localTool:
            name: "elw"
            audience: "https://api.brightspace.com/auth/token"
            oidc_initiation_url: "https://elw.uga.edu/lti1p3/oidc/initiation"
            launch_url: "https://elw.uga.edu/lti_test"
            deep_linking_url: null
    registrations:
        ugatest2:
            client_id: "b9bf54c6-8856-4a03-b4c5-d4b52cee3b84"
            platform: "ugatest2"
            tool: "localTool"
            deployment_ids:
                - "ce0f6d44-e598-4400-a2bd-ce6884eb416d"
            platform_key_chain: ~
            platform_jwks_url: "https://ugatest2.view.usg.edu/d2l/.well-known/jwks"
            tool_key_chain: "toolKey"
            tool_jwks_url: "https://elw.uga.edu/lti1p3/.well-known/jwks/toolSet.json"
        elc:
            client_id: "04f3627d-9d0d-48b4-aaee-05cbbf3407e5"
            platform: "elc"
            tool: "localTool"
            deployment_ids:
                - "98bc1d03-b059-43d3-b94d-ad0c2d00c7ea"
            platform_key_chain: ~
            platform_jwks_url: "https://uga.view.usg.edu/d2l/.well-known/jwks"
            tool_key_chain: "toolKey"
            tool_jwks_url: "https://elw.uga.edu/lti1p3/.well-known/jwks/toolSet.json"