security:
  providers:
    users:
      entity:
        # the class of the entity that represents users
        class: 'App\Entity\User'
        # the property to query by - e.g. username, email, etc
        property: 'username'
  encoders:
    App\Entity\User:
      algorithm: auto
  firewalls:
    main:
      logout:
        path: /logout
        target: /app_login
      anonymous: ~
      lti1p3_message_tool: true
      guard:
        entry_point: App\Security\LoginFormAuthenticator
        authenticators:
          - App\Security\LoginFormAuthenticator
          - App\Security\LtiAuthenticator
      switch_user: true

  access_control:
    - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
    - { path: ^/home, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
    - { path: ^/lti1p3, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
    - { path: ^/course, roles: ROLE_USER, requires_channel: https}
    - { path: ^/journal, roles: ROLE_USER, requires_channel: https}
    - { path: ^/classlist, roles: ROLE_USER, requires_channel: https }
    - { path: ^/doc, roles: ROLE_USER, requires_channel: https }
    - { path: ^/admin, roles: ROLE_ADMIN, requires_channel: https }
    - { path: ^/card, roles: ROLE_ADMIN, requires_channel: https }
    - { path: ^/label, roles: ROLE_INSTRUCTOR, requires_channel: https }
    - { path: ^/markupset, roles: ROLE_INSTRUCTOR, requires_channel: https }
    - { path: ^/markup, roles: ROLE_INSTRUCTOR, requires_channel: https }
    - { path: ^/rubric, roles: ROLE_INSTRUCTOR, requires_channel: https }
    - { path: ^/comment, roles: ROLE_USER, requires_channel: https }
    - { path: ^/rating, roles: ROLE_USER, requires_channel: https }
    - { path: ^/stage, roles: ROLE_INSTRUCTOR, requires_channel: https }
    - { path: ^/term, roles: ROLE_ADMIN, requires_channel: https }