index:
    path: /
    controller: App\Controller\DefaultController::index

app_logout:
    path: /logout
    methods: GET

platform_service:
    path: /tool/launch
    controller: App\Action\Tool\LtiLaunchAction

